/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_cnr_istc_pst_oratio_timelines_TimelinesExecutor */

#ifndef _Included_it_cnr_istc_pst_oratio_timelines_TimelinesExecutor
#define _Included_it_cnr_istc_pst_oratio_timelines_TimelinesExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_cnr_istc_pst_oratio_timelines_TimelinesExecutor
 * Method:    new_instance
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_it_cnr_istc_pst_oratio_timelines_TimelinesExecutor_new_1instance
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     it_cnr_istc_pst_oratio_timelines_TimelinesExecutor
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_it_cnr_istc_pst_oratio_timelines_TimelinesExecutor_dispose
  (JNIEnv *, jobject);

/*
 * Class:     it_cnr_istc_pst_oratio_timelines_TimelinesExecutor
 * Method:    tick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_it_cnr_istc_pst_oratio_timelines_TimelinesExecutor_tick
  (JNIEnv *, jobject);

/*
 * Class:     it_cnr_istc_pst_oratio_timelines_TimelinesExecutor
 * Method:    done
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_it_cnr_istc_pst_oratio_timelines_TimelinesExecutor_done
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     it_cnr_istc_pst_oratio_timelines_TimelinesExecutor
 * Method:    failure
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_it_cnr_istc_pst_oratio_timelines_TimelinesExecutor_failure
  (JNIEnv *, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
