/*
 * Copyright (C) 2018 Riccardo De Benedictis <riccardo.debenedictis@istc.cnr.it>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.cnr.istc.oratio.gui;

import it.cnr.istc.oratio.Rational;
import it.cnr.istc.oratio.gui.riddle.Core;
import it.cnr.istc.oratio.gui.state.StateTreeNode;
import java.awt.EventQueue;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.event.TreeExpansionEvent;
import javax.swing.event.TreeModelEvent;
import javax.swing.event.TreeModelListener;
import javax.swing.event.TreeWillExpandListener;
import javax.swing.tree.ExpandVetoException;

/**
 *
 * @author Riccardo De Benedictis <riccardo.debenedictis@istc.cnr.it>
 */
public class ORatioJFrame extends javax.swing.JFrame {

    private static final String FLAW_CREATED = "flaw_created ";
    private static final String FLAW_STATE_CHANGED = "flaw_state_changed ";
    private static final String CURRENT_FLAW = "current_flaw ";
    private static final String RESOLVER_CREATED = "resolver_created ";
    private static final String RESOLVER_STATE_CHANGED = "resolver_state_changed ";
    private static final String RESOLVER_COST_CHANGED = "resolver_cost_changed ";
    private static final String CURRENT_RESOLVER = "current_resolver ";
    private static final String CAUSAL_LINK_ADDED = "causal_link_added ";
    private static final String STATE_CHANGED = "state_changed ";

    /**
     * Creates new form ORatioJFrame
     *
     * @param args a string array containing the riddle files
     */
    public ORatioJFrame(String[] args) {
        initComponents();

        mainDesktopPane.add(state_frame);
        mainDesktopPane.add(graph_frame);

        state_frame.setBounds(50, 50, 300, 250);
        graph_frame.setBounds(400, 50, 300, 250);

        state_tree_model.addTreeModelListener(new TreeModelListener() {
            @Override
            public void treeNodesChanged(TreeModelEvent e) {
            }

            @Override
            public void treeNodesInserted(TreeModelEvent e) {
            }

            @Override
            public void treeNodesRemoved(TreeModelEvent e) {
            }

            @Override
            public void treeStructureChanged(TreeModelEvent e) {
                stateTree.expandRow(0);
            }
        });
        stateTree.addTreeWillExpandListener(new TreeWillExpandListener() {
            @Override
            public void treeWillExpand(TreeExpansionEvent event) throws ExpandVetoException {
                StateTreeNode etn = (StateTreeNode) event.getPath().getLastPathComponent();
                if (!etn.hasLoadedChildren()) {
                    etn.loadChildren();
                }
            }

            @Override
            public void treeWillCollapse(TreeExpansionEvent event) throws ExpandVetoException {
            }
        });

        javax.swing.ToolTipManager.sharedInstance().registerComponent(stateTree);

        if (args.length > 0) {
            System.out.println("reading riddle files..");
            try {
                core.read(Stream.of(args).map(arg -> new File(arg)).toArray(File[]::new));
            } catch (IOException ex) {
                Logger.getLogger(ORatioJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        core = new it.cnr.istc.oratio.gui.riddle.Core();
        deserializer = new it.cnr.istc.oratio.gui.riddle.CoreDeserializer();
        builder = new com.google.gson.GsonBuilder();
        builder.registerTypeAdapter(Core.class, deserializer);
        gson = builder.create();
        state_tree_model = new it.cnr.istc.oratio.gui.state.StateTreeModel();
        state_tree_cell_renderer = new it.cnr.istc.oratio.gui.state.StateTreeCellRenderer();
        graph_frame = new javax.swing.JInternalFrame();
        graph = new it.cnr.istc.oratio.gui.graph.CausalGraph();
        state_frame = new javax.swing.JInternalFrame();
        stateTreeScrollPane = new javax.swing.JScrollPane();
        stateTree = new javax.swing.JTree();
        mainDesktopPane = new javax.swing.JDesktopPane();

        state_tree_cell_renderer.setText("stateTreeCellRenderer1");

        graph_frame.setIconifiable(true);
        graph_frame.setMaximizable(true);
        graph_frame.setResizable(true);
        graph_frame.setTitle("Causal graph");
        graph_frame.setVisible(true);

        javax.swing.GroupLayout graph_frameLayout = new javax.swing.GroupLayout(graph_frame.getContentPane());
        graph_frame.getContentPane().setLayout(graph_frameLayout);
        graph_frameLayout.setHorizontalGroup(
            graph_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        graph_frameLayout.setVerticalGroup(
            graph_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        state_frame.setIconifiable(true);
        state_frame.setMaximizable(true);
        state_frame.setResizable(true);
        state_frame.setTitle("State");
        state_frame.setVisible(true);

        stateTree.setModel(state_tree_model);
        stateTree.setCellRenderer(state_tree_cell_renderer);
        stateTree.setRootVisible(false);
        stateTreeScrollPane.setViewportView(stateTree);

        javax.swing.GroupLayout state_frameLayout = new javax.swing.GroupLayout(state_frame.getContentPane());
        state_frame.getContentPane().setLayout(state_frameLayout);
        state_frameLayout.setHorizontalGroup(
            state_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stateTreeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );
        state_frameLayout.setVerticalGroup(
            state_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stateTreeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("oRatio");
        setIconImages(Arrays.asList(new ImageIcon(getClass().getResource("/oRatio16.png")).getImage(), new ImageIcon(getClass().getResource("/oRatio32.png")).getImage()));

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ORatioJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ORatioJFrame frame = new ORatioJFrame(args);
        EventQueue.invokeLater(() -> frame.setVisible(true));

        System.out.println("starting GUI server..");
        try (ServerSocket ss = new ServerSocket(1100); Socket client = ss.accept(); BufferedReader in = new BufferedReader(new InputStreamReader(client.getInputStream(), "UTF-8"))) {
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                if (inputLine.startsWith(FLAW_CREATED)) {
                    FlawCreated fc = frame.gson.fromJson(inputLine.substring(FLAW_CREATED.length()), FlawCreated.class);
                    frame.graph.flaw_created(fc.flaw, fc.causes, fc.label, fc.state);
                } else if (inputLine.startsWith(FLAW_STATE_CHANGED)) {
                    FlawStateChanged fsc = frame.gson.fromJson(inputLine.substring(FLAW_STATE_CHANGED.length()), FlawStateChanged.class);
                    frame.graph.flaw_state_changed(fsc.flaw, fsc.state);
                } else if (inputLine.startsWith(CURRENT_FLAW)) {
                    CurrentFlaw cf = frame.gson.fromJson(inputLine.substring(CURRENT_FLAW.length()), CurrentFlaw.class);
                    frame.graph.current_flaw(cf.flaw);
                } else if (inputLine.startsWith(RESOLVER_CREATED)) {
                    ResolverCreated rc = frame.gson.fromJson(inputLine.substring(RESOLVER_CREATED.length()), ResolverCreated.class);
                    frame.graph.resolver_created(rc.resolver, rc.effect, rc.cost, rc.label, rc.state);
                } else if (inputLine.startsWith(RESOLVER_STATE_CHANGED)) {
                    ResolverStateChanged rsc = frame.gson.fromJson(inputLine.substring(RESOLVER_STATE_CHANGED.length()), ResolverStateChanged.class);
                    frame.graph.resolver_state_changed(rsc.resolver, rsc.state);
                } else if (inputLine.startsWith(RESOLVER_COST_CHANGED)) {
                    ResolverCostChanged rcc = frame.gson.fromJson(inputLine.substring(RESOLVER_COST_CHANGED.length()), ResolverCostChanged.class);
                    frame.graph.resolver_cost_changed(rcc.resolver, rcc.cost);
                } else if (inputLine.startsWith(CURRENT_RESOLVER)) {
                    CurrentResolver cr = frame.gson.fromJson(inputLine.substring(CURRENT_RESOLVER.length()), CurrentResolver.class);
                    frame.graph.current_resolver(cr.resolver);
                } else if (inputLine.startsWith(CAUSAL_LINK_ADDED)) {
                    CausalLinkAdded cla = frame.gson.fromJson(inputLine.substring(CAUSAL_LINK_ADDED.length()), CausalLinkAdded.class);
                    frame.graph.causal_link_added(cla.flaw, cla.resolver);
                } else if (inputLine.startsWith(STATE_CHANGED)) {
                    frame.deserializer.setCore(frame.core);
                    frame.core = frame.gson.fromJson(inputLine.substring(STATE_CHANGED.length()), Core.class);
                    frame.state_tree_model.setCore(frame.core);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(ORatioJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.google.gson.GsonBuilder builder;
    private it.cnr.istc.oratio.gui.riddle.Core core;
    private it.cnr.istc.oratio.gui.riddle.CoreDeserializer deserializer;
    private it.cnr.istc.oratio.gui.graph.CausalGraph graph;
    private javax.swing.JInternalFrame graph_frame;
    private com.google.gson.Gson gson;
    private javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JTree stateTree;
    private javax.swing.JScrollPane stateTreeScrollPane;
    private javax.swing.JInternalFrame state_frame;
    private it.cnr.istc.oratio.gui.state.StateTreeCellRenderer state_tree_cell_renderer;
    private it.cnr.istc.oratio.gui.state.StateTreeModel state_tree_model;
    // End of variables declaration//GEN-END:variables

    static class FlawCreated {

        private String flaw;
        private String[] causes;
        private String label;
        private int state;
    }

    static class FlawStateChanged {

        private String flaw;
        private int state;
    }

    static class CurrentFlaw {

        private String flaw;
    }

    static class ResolverCreated {

        private String resolver;
        private String effect;
        private Rational cost;
        private String label;
        private int state;
    }

    static class ResolverStateChanged {

        private String resolver;
        private int state;
    }

    static class ResolverCostChanged {

        private String resolver;
        private Rational cost;
    }

    static class CurrentResolver {

        private String resolver;
    }

    static class CausalLinkAdded {

        private String flaw;
        private String resolver;
    }
}
